FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY alembic.ini /app/alembic.ini
COPY app /app/app
COPY db /app/db
COPY scripts /app/scripts
COPY config /app/config

EXPOSE 8000

CMD ["sh","-lc","python scripts/init_db.py && uvicorn app.api.app:app --host 0.0.0.0 --port 8000"]

